# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/glide/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/samsung/glide/proprietary/libril.so:obj/lib/libril.so \
    vendor/samsung/glide/proprietary/libsecril-client.so:obj/lib/libsecril-client.so

# HAL
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/lib/hw/gralloc.tegra.so:system/lib/hw/gralloc.tegra.so \
    vendor/samsung/glide/proprietary/lib/hw/hwcomposer.tegra.so:system/lib/hw/hwcomposer.tegra.so \
    vendor/samsung/glide/proprietary/lib/hw/gps.tegra.so:system/lib/hw/gps.tegra.so \
    vendor/samsung/glide/proprietary/lib/hw/camera.tegra.so:system/lib/hw/camera.tegra.so \
    vendor/samsung/glide/proprietary/lib/hw/sensors.n1.so:system/lib/hw/sensors.n1.so

# EGL
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/lib/egl/libEGL_tegra.so:system/lib/egl/libEGL_tegra.so \
    vendor/samsung/glide/proprietary/lib/egl/libEGL_perfhud.so:system/lib/egl/libEGL_perfhud.so \
    vendor/samsung/glide/proprietary/lib/egl/libGLESv1_CM_tegra.so:system/lib/egl/libGLESv1_CM_tegra.so \
    vendor/samsung/glide/proprietary/lib/egl/libGLESv1_CM_perfhud.so:system/lib/egl/libGLESv1_CM_perfhud.so \
    vendor/samsung/glide/proprietary/lib/egl/libGLESv2_tegra.so:system/lib/egl/libGLESv2_tegra.so \
    vendor/samsung/glide/proprietary/lib/egl/libGLESv2_perfhud.so:system/lib/egl/libGLESv2_perfhud.so

# RIL files
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/libril.so:system/lib/libril.so \
    vendor/samsung/glide/proprietary/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/glide/proprietary/libsecril-client.so:system/lib/libsecril-client.so

# SENSORS
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/libakm.so:system/lib/libakm.so \
    vendor/samsung/glide/proprietary/libmpl.so:system/lib/libmpl.so \
    vendor/samsung/glide/proprietary/libmllite.so:system/lib/libmllite.so \
    vendor/samsung/glide/proprietary/libmlplatform.so:system/lib/libmlplatform.so

# WIFI
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/bcm4330_apsta.bin:system/etc/wifi/bcm4330_apsta.bin \
    vendor/samsung/glide/proprietary/bcm4330_mfg.bin:system/etc/wifi/bcm4330_mfg.bin \
    vendor/samsung/glide/proprietary/bcm4330_p2p.bin:system/etc/wifi/bcm4330_p2p.bin \
    vendor/samsung/glide/proprietary/bcm4330_sta.bin:system/etc/wifi/bcm4330_sta.bin \
    vendor/samsung/glide/proprietary/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/glide/proprietary/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/glide/proprietary/wlandutservice:system/bin/wlandutservice \
    vendor/samsung/glide/proprietary/macloader:system/bin/macloader \
    vendor/samsung/glide/proprietary/mfgloader:system/bin/mfgloader \
    vendor/samsung/glide/proprietary/nv_hciattach:system/bin/nv_hciattach

# NVIDIA
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/libnvapputil.so:system/lib/libnvapputil.so \
    vendor/samsung/glide/proprietary/libnvasfparserhal.so:system/lib/libnvasfparserhal.so \
    vendor/samsung/glide/proprietary/libnvaviparserhal.so:system/lib/libnvaviparserhal.so \
    vendor/samsung/glide/proprietary/libnvavp.so:system/lib/libnvavp.so \
    vendor/samsung/glide/proprietary/libnvos.so:system/lib/libnvos.so \
    vendor/samsung/glide/proprietary/libnvomx.so:/system/lib/libnvomx.so \
    vendor/samsung/glide/proprietary/libnvomxadaptor.so:system/lib/libnvomxadaptor.so \
    vendor/samsung/glide/proprietary/libnvomxilclient.so:system/lib/libnvomxilclient.so \
    vendor/samsung/glide/proprietary/libnvrm.so:system/lib/libnvrm.so \
    vendor/samsung/glide/proprietary/libnvrm_graphics.so:system/lib/libnvrm_graphics.so \
    vendor/samsung/glide/proprietary/libnvddk_2d_v2.so:system/lib/libnvddk_2d_v2.so \
    vendor/samsung/glide/proprietary/libnvddk_2d.so:system/lib/libnvddk_2d.so \
    vendor/samsung/glide/proprietary/libnvmm.so:/system/lib/libnvmm.so \
    vendor/samsung/glide/proprietary/libnvmm_asfparser.so:/system/lib/libnvmm_asfparser.so \
    vendor/samsung/glide/proprietary/libnvmm_audio.so:/system/lib/libnvmm_audio.so \
    vendor/samsung/glide/proprietary/libnvmm_aviparser.so:/system/lib/libnvmm_aviparser.so \
    vendor/samsung/glide/proprietary/libnvmm_camera.so:/system/lib/libnvmm_camera.so \
    vendor/samsung/glide/proprietary/libnvmm_contentpipe.so:/system/lib/libnvmm_contentpipe.so \
    vendor/samsung/glide/proprietary/libnvmm_image.so:/system/lib/libnvmm_image.so \
    vendor/samsung/glide/proprietary/libnvmm_manager.so:/system/lib/libnvmm_manager.so \
    vendor/samsung/glide/proprietary/libnvmm_msaudio.so:/system/lib/libnvmm_msaudio.so \
    vendor/samsung/glide/proprietary/libnvmm_parser.so:/system/lib/libnvmm_parser.so \
    vendor/samsung/glide/proprietary/libnvmm_service.so:/system/lib/libnvmm_service.so \
    vendor/samsung/glide/proprietary/libnvmm_utils.so:/system/lib/libnvmm_utils.so \
    vendor/samsung/glide/proprietary/libnvmm_vc1_video.so:system/lib/libnvmm_vc1_video.so \
    vendor/samsung/glide/proprietary/libnvmm_video.so:/system/lib/libnvmm_video.so \
    vendor/samsung/glide/proprietary/libnvmm_writer.so:/system/lib/libnvmm_writer.so \
    vendor/samsung/glide/proprietary/libnvmmlite.so:/system/lib/libnvmmlite.so \
    vendor/samsung/glide/proprietary/libnvmmlite_audio.so:/system/lib/libnvmmlite_audio.so \
    vendor/samsung/glide/proprietary/libnvmmlite_utils.so:/system/lib/libnvmmlite_utils.so \
    vendor/samsung/glide/proprietary/libnvmmlite_video.so:/system/lib/libnvmmlite_video.so \
    vendor/samsung/glide/proprietary/libnvodm_dtvtuner.so:/system/lib/libnvodm_dtvtuner.so \
    vendor/samsung/glide/proprietary/libnvodm_hdmi.so:/system/lib/libnvodm_hdmi.so \
    vendor/samsung/glide/proprietary/libnvodm_imager.so:/system/lib/libnvodm_imager.so \
    vendor/samsung/glide/proprietary/libnvodm_misc.so:/system/lib/libnvodm_misc.so \
    vendor/samsung/glide/proprietary/libnvodm_query.so:/system/lib/libnvodm_query.so \
    vendor/samsung/glide/proprietary/libnvparser.so:/system/lib/libnvparser.so \
    vendor/samsung/glide/proprietary/libnvsm.so:/system/lib/libnvsm.so \
    vendor/samsung/glide/proprietary/libnvtestio.so:/system/lib/libnvtestio.so \
    vendor/samsung/glide/proprietary/libnvtestresults.so:/system/lib/libnvtestresults.so \
    vendor/samsung/glide/proprietary/libnvtvmr.so:/system/lib/libnvtvmr.so \
    vendor/samsung/glide/proprietary/libnvwinsys.so:/system/lib/libnvwinsys.so \
    vendor/samsung/glide/proprietary/libnvwsi.so:/system/lib/libnvwsi.so \
    vendor/samsung/glide/proprietary/libcgdrv.so:/system/lib/libcgdrv.so \
    vendor/samsung/glide/proprietary/libardrv_dynamic.so:system/lib/libardrv_dynamic.so

# Firmwares
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/firmware/nvmm_aacdec.axf:system/etc/firmware/nvmm_aacdec.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_adtsdec.axf:system/etc/firmware/nvmm_adtsdec.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_h264dec.axf:system/etc/firmware/nvmm_h264dec.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_jpegdec.axf:system/etc/firmware/nvmm_jpegdec.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_jpegenc.axf:system/etc/firmware/nvmm_jpegenc.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_manager.axf:system/etc/firmware/nvmm_manager.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_mp3dec.axf:system/etc/firmware/nvmm_mp3dec.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_mpeg4dec.axf:system/etc/firmware/nvmm_mpeg4dec.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_service.axf:system/etc/firmware/nvmm_service.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_vc1dec.axf:system/etc/firmware/nvmm_vc1dec.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_vc1dec_2x.axf:system/etc/firmware/nvmm_vc1dec_2x.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_wavdec.axf:system/etc/firmware/nvmm_wavdec.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_wmadec.axf:system/etc/firmware/nvmm_wmadec.axf \
    vendor/samsung/glide/proprietary/firmware/nvmm_wmaprodec.axf:system/etc/firmware/nvmm_wmaprodec.axf \
    vendor/samsung/glide/proprietary/firmware/nvrm_avp.bin:system/etc/firmware/nvrm_avp.bin \
    vendor/samsung/glide/proprietary/firmware/bcm4330.hcd:system/etc/firmware/bcm4330.hcd

# OMX
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/libsomxcmn.so:system/lib/libsomxcmn.so \
    vendor/samsung/glide/proprietary/libsomxcore.so:system/lib/libsomxcore.so \
    vendor/samsung/glide/proprietary/libsomxaacd.so:system/lib/libsomxaacd.so \
    vendor/samsung/glide/proprietary/libsomxaace.so:system/lib/libsomxaace.so \
    vendor/samsung/glide/proprietary/libsomxac3d.so:system/lib/libsomxac3d.so \
    vendor/samsung/glide/proprietary/libsomxamrd.so:system/lib/libsomxamrd.so \
    vendor/samsung/glide/proprietary/libsomxflacd.so:system/lib/libsomxflacd.so \
    vendor/samsung/glide/proprietary/libsomxmp3d.so:system/lib/libsomxmp3d.so \
    vendor/samsung/glide/proprietary/libsomxmp43d.so:system/lib/libsomxmp43d.so \
    vendor/samsung/glide/proprietary/libsomxsr263d.so:system/lib/libsomxsr263d.so \
    vendor/samsung/glide/proprietary/libsomxwmad.so:system/lib/libsomxwmad.so \
    vendor/samsung/glide/proprietary/libsomxwmv7d.so:system/lib/libsomxwmv7d.so \
    vendor/samsung/glide/proprietary/libsomxwmv8d.so:system/lib/libsomxwmv8d.so

PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/libsavsac.so:system/lib/libsavsac.so \
    vendor/samsung/glide/proprietary/libsavscmn.so:system/lib/libsavscmn.so \
    vendor/samsung/glide/proprietary/libsavsff.so:system/lib/libsavsff.so \
    vendor/samsung/glide/proprietary/libsavsmeta.so:system/lib/libsavsmeta.so \
    vendor/samsung/glide/proprietary/libsavsvc.so:system/lib/libsavsvc.so \
    vendor/samsung/glide/proprietary/libsAMRNB.so:system/lib/libsAMRNB.so \
    vendor/samsung/glide/proprietary/libsAMRWB.so:system/lib/libsAMRWB.so \
    vendor/samsung/glide/proprietary/libsthmb.so:system/lib/libsthmb.so

PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/libstagefrighthw.so:system/lib/libstagefrighthw.so

# Camera
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/glide/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv

# BT
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/brcm_patchram_plus:system/bin/brcm_patchram_plus

# TVOut
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/bintvoutservice:system/bin/bintvoutservice \
    vendor/samsung/glide/proprietary/libtvoutinterface.so:system/lib/libtvoutinterface.so \
    vendor/samsung/glide/proprietary/libtvoutservice.so:system/lib/libtvoutservice.so \
    vendor/samsung/glide/proprietary/libtvout_jni.so:system/lib/libtvout_jni.so

# Other files
PRODUCT_COPY_FILES += \
    vendor/samsung/glide/proprietary/immvibed:system/bin/immvibed \
    vendor/samsung/glide/proprietary/drexe:system/bin/drexe \
    vendor/samsung/glide/proprietary/npsmobex:system/bin/npsmobex \
    vendor/samsung/glide/proprietary/nvcpud:system/bin/nvcpud

PRODUCT_COPY_FILES += \
    vendor/samsung/glide/lpm/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/glide/lpm/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/glide/lpm/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/glide/lpm/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/glide/lpm/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/glide/lpm/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/glide/lpm/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/glide/lpm/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/glide/lpm/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/glide/lpm/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/glide/lpm/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/glide/lpm/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/glide/lpm/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/glide/lpm/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/glide/lpm/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/glide/lpm/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/glide/lpm/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/glide/lpm/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/glide/lpm/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/glide/lpm/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/glide/lpm/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/glide/lpm/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/glide/lpm/Disconnected.qmg:system/media/Disconnected.qmg

